use std::collections::BTreeSet;

use prikk_object::{NodeId, NodeKind, ObjectId};

use crate::path::RepoPath;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum PairClass {
    Independent,
    OrderedDependency {
        required_order: RequiredOrder,
        witness: ConflictWitness,
    },
    Conflict {
        witness: ConflictWitness,
    },
    Unknown {
        reason: UnknownReason,
        witness: ConflictWitness,
    },
}

pub(crate) type CommutationAnalysisResult =
    std::result::Result<CommutationResult, super::evidence_types::EvidenceError>;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum CommutationResult {
    Commutes { proof: CommutationProof },
    DoesNotCommute { pair_class: PairClass },
    Unknown { reason: UnknownReason },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct CommutationProof {
    pub(crate) left_op_seq: u32,
    pub(crate) right_op_seq: u32,
}

pub(crate) type ConfluenceAnalysisResult =
    std::result::Result<ConfluenceResult, super::evidence_types::EvidenceError>;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ConfluenceResult {
    Confluent { proof: ConfluenceProof },
    NotConfluent { witness: ConfluenceWitness },
    Unknown { reason: UnknownReason },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ConfluenceProof {
    pub(crate) left_len: usize,
    pub(crate) right_len: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ConfluenceWitness {
    pub(crate) kind: ConfluenceWitnessKind,
    pub(crate) left_index: Option<usize>,
    pub(crate) right_index: Option<usize>,
    pub(crate) pair_class: Option<PairClass>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ConfluenceWitnessKind {
    OrderedDependency,
    Conflict,
    ReplayFailure,
    FinalStateInequality,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RequiredOrder {
    LeftBeforeRight,
    RightBeforeLeft,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ConflictWitness {
    pub(crate) kind: ConflictWitnessKind,
    pub(crate) left_op_seq: u32,
    pub(crate) right_op_seq: u32,
    pub(crate) node_id: Option<NodeId>,
    pub(crate) path: Option<RepoPath>,
    pub(crate) text_span: Option<[u8; 32]>,
}

// Conflict-witness-presentation handoff v1 §4, applying RFC 118 stages 4/5's pattern:
// `ConflictWitnessKind`, its `ALL`, and its `label()` are generated together from the single
// variant list below, in one macro expansion, rather than three separately hand-maintained lists a
// hand-added variant could silently omit from one or two of. A thirteenth kind cannot be added to
// the enum without simultaneously giving it a label; there is nowhere else to add it and nothing
// else to keep in sync. Deliberately not the *same* macro invocation `VerificationStage` uses --
// that one is hardcoded to `pub enum VerificationStage`, not parameterized over an enum name --
// this is a new, structurally identical macro, colocated with the enum it generates.
macro_rules! conflict_witness_kinds {
    (
        $(
            $(#[$doc:meta])*
            $variant:ident => $label:literal,
        )+
    ) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub(crate) enum ConflictWitnessKind {
            $(
                $(#[$doc])*
                $variant,
            )+
        }

        impl ConflictWitnessKind {
            /// Every kind, in declaration order. Generated by this enum's own defining macro
            /// invocation, not a second, independently maintained list -- used only by
            /// `every_conflict_witness_kind_reaches_the_report_item` today (a completeness sweep,
            /// not production code), hence the `cfg` below.
            #[cfg_attr(not(test), allow(dead_code))]
            pub(crate) const ALL: &'static [Self] = &[$(Self::$variant),+];

            /// Stable kebab-case label. **An external interface** once a conflict witness reaches
            /// `MergeEvidenceDisplayItem::witness_kind` (conflict-witness-presentation handoff v1)
            /// -- renaming, removing, or reusing one is a breaking change to any tool reading it,
            /// the same footing `VerificationStage::label()` is on.
            #[must_use]
            pub(crate) const fn label(self) -> &'static str {
                match self {
                    $(Self::$variant => $label,)+
                }
            }
        }
    };
}

conflict_witness_kinds! {
    SamePathCreate => "same-path-create",
    /// RFC 144 §4o.5 (the thirteenth): both sides rename the *same* node to two *disjoint*
    /// destinations. Distinct from `SamePathCreate` by design (§4i.2's own dual): "one node, two
    /// paths -- pick the path" versus `SamePathCreate`'s "two nodes, one path -- pick the node".
    RenameDestinationConflict => "rename-destination-conflict",
    NodeIdReuse => "node-id-reuse",
    LiveStateMismatch => "live-state-mismatch",
    KindMismatch => "kind-mismatch",
    ModeMismatch => "mode-mismatch",
    BlobMismatch => "blob-mismatch",
    TextSpanOverlap => "text-span-overlap",
    TextAnchorStale => "text-anchor-stale",
    DeleteMutationConflict => "delete-mutation-conflict",
    UnsupportedOperation => "unsupported-operation",
    MalformedOperation => "malformed-operation",
    UnknownRelation => "unknown-relation",
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum UnknownReason {
    MalformedOperation,
    SameNodeTextCommutationDeferred,
    RenameDeferred,
    SymlinkDeferred,
    #[cfg(test)]
    FuturePreconditionDeferred,
    MissingCandidateEvidence,
    SequenceInternalDependencyDeferred,
    UnknownRelation,
}

#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub(crate) struct PathEffects {
    pub(crate) occupied_before: BTreeSet<RepoPath>,
    pub(crate) required_free: BTreeSet<RepoPath>,
    pub(crate) occupied_after: BTreeSet<RepoPath>,
    pub(crate) freed: BTreeSet<RepoPath>,
    pub(crate) newly_occupied: BTreeSet<RepoPath>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct OperationFacts {
    pub(super) op_seq: u32,
    pub(super) node_id: Option<NodeId>,
    pub(super) action: Action,
    pub(super) path_effects: PathEffects,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) enum Action {
    CreateFile {
        path: RepoPath,
        node_id: NodeId,
        blob_id: ObjectId,
        mode: u32,
    },
    DeleteFile {
        path: RepoPath,
        node_id: NodeId,
        old_node_kind: NodeKind,
        old_blob_id: prikk_object::ObjectId,
        old_mode: u32,
    },
    DeleteSymlink {
        path: RepoPath,
        node_id: NodeId,
    },
    EditText {
        node_id: NodeId,
        span_id: [u8; 32],
        old_span_hash: [u8; 32],
        left_anchor_hash: [u8; 32],
        right_anchor_hash: [u8; 32],
        old_span_text: Vec<u8>,
        /// RFC 134 §8: see `DecodedOperationKind::EditText`.
        left_anchor_len: Option<u32>,
        right_anchor_len: Option<u32>,
    },
    ReplaceBinary {
        node_id: NodeId,
        old_blob_id: prikk_object::ObjectId,
        new_blob_id: prikk_object::ObjectId,
    },
    RenamePath {
        node_id: NodeId,
        /// RFC 144 §4o.5: the destination is load-bearing for classification, not just an
        /// authoring detail -- the thirteenth conflict witness (two renames of one node to
        /// disjoint destinations) cannot be computed without it, since `PathEffects` alone
        /// (`newly_occupied`/`occupied_after`/`required_free`) does not recover which node a
        /// destination belongs to.
        new_path: RepoPath,
    },
    ChangePerm {
        node_id: NodeId,
        old_mode: u32,
        new_mode: u32,
    },
    CreateSymlink {
        path: RepoPath,
        node_id: NodeId,
    },
}
